services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: postgres-pedidos
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  django:
    build:
      context: ./backend
    container_name: django-pedidos
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment: 
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      backend_network:
        aliases:
          - django

  # wso2mi:
  #   image: wso2mi_1.0.0  # sua imagem personalizada 
  #   container_name: wso2mi-2
  #   ports:
  #     - "8290:8290"
  #     - "8253:8253"
  #   restart: always
  #   depends_on:
  #     - django
  #   networks:
  #     - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
