openapi: 3.0.1
info:
  title: pedidoReq
  description: API Definition of pedidoReq
  version: 1.0.0
servers:
- url: http://localhost:8290/pedido
paths:
  /:
    get:
      responses:
        default:
          description: Default response
