# Generated by Django 4.2.20 on 2025-03-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.AlterField(
            model_name='tipopedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
